version: '3.8'

services:
  osuReports:
    image: ajmadsen/osureports
    restart: unless-stopped
    env_file: .env
    ports:
      - '3000:3000'
    volumes:
      - ./data:/data
    environment:
      DATABASE: /data/osuReports.db
      REDIS_HOST: redis

  redis:
    image: redis:6.0
    restart: unless-stopped
    expose:
      - 6379
    volumes:
      - 'redis-data:/data'

volumes:
  redis-data:
