version: "3.8"

services:
  osuReports:
    image: ajmadsen/osureports
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data
    environment:
      DATABASE: /data/osuReports.db
      REDIS_HOST: redis

  redis:
    image: redis:6.0
    restart: unless-stopped
    expose:
      - 6379
    volumes:
      - "redis-data:/data"

  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--storage.tsdb.retention.time=1y"

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - "3010:3000"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  redis-data:
  grafana-data:
  prometheus-data:
