global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 1m

scrape_configs:
  - job_name: osuReports
    static_configs:
      - targets:
          - osuReports:9010

  - job_name: redis_exporter
    static_configs:
      - targets:
          - redis-exporter:9121

  - job_name: nginx_exporter
    static_configs:
      - targets:
          - nginx-exporter:9913

  - job_name: node-exporter
    static_configs:
      - targets:
          - 172.19.0.1:9100
