name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  IMAGE: ajmadsen/osureports
  WEB_IMAGE: ajmadsen/osureports-web

jobs:
  build-worker:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(toJson(github.event.commits), '***NO_CI***') == false && contains(toJson(github.event.commits), '[ci skip]') == false && contains(toJson(github.event.commits), '[skip ci]') == false

    steps:
      - uses: actions/checkout@v2
      - uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ajmadsen
          password: "${{ secrets.DOCKER_TOKEN }}"
          image_name: "${{ env.IMAGE }}"
          push_image_and_stages: "${{ github.base_ref == '' }}"

  build-web:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(toJson(github.event.commits), '***NO_CI***') == false && contains(toJson(github.event.commits), '[ci skip]') == false && contains(toJson(github.event.commits), '[skip ci]') == false

    steps:
      - uses: actions/checkout@v2
      - uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ajmadsen
          password: "${{ secrets.DOCKER_TOKEN }}"
          image_name: "${{ env.WEB_IMAGE }}"
          dockerfile: "Dockerfile.web"
          push_image_and_stages: "${{ github.base_ref == '' }}"
